# Generated by Django 2.0.13 on 2019-06-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('date', models.DateField(verbose_name='Data')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
                ('code', models.CharField(max_length=255, verbose_name='Código')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Descrição Curta')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='eventimage/%Y/%m/%d/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
