# Generated by Django 2.0.13 on 2019-05-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='code',
            field=models.CharField(default='JOAOV', max_length=255, verbose_name='Código'),
            preserve_default=False,
        ),
    ]
