# Generated by Django 2.0.13 on 2019-05-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_event_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(default='', max_length=255, verbose_name='Link'),
            preserve_default=False,
        ),
    ]
